version: "3.5"
services:

  motioneye:
    image: ccrisan/motioneye:master-amd64  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    ports:
      - "8765:8765"
      - "8081:8081"
    volumes:
      - etc_motioneye:/etc/motioneye
      - var_lib_motioneye:/var/lib/motioneye
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.motion.middlewares=https-only-motion"
      - "traefik.http.middlewares.https-only-motion.redirectscheme.scheme=https"
      - "traefik.http.routers.motion.rule=Host(`cam.galoubenj.top`)"
      - "traefik.http.routers.motion.entrypoints=web"
      - "traefik.http.routers.motion-secured.rule=Host(`cam.galoubenj.top`)"                                                                                                                                                                
      - "traefik.http.routers.motion-secured.entrypoints=websecure"
      - "traefik.http.routers.motion-secured.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.motioneye.loadbalancer.server.port=8765"
      - "traefik.docker.network=traefik_webgateway"
    networks: 
      - webgateway
        
volumes: 
  etc_motioneye:
  var_lib_motioneye:  
  
networks: 
  webgateway:
    external:
      name: traefik_webgateway